version: '3.8'
services:
  postgres:
    image: postgres:16.4
    restart: always
    environment:
      - POSTGRES_USER=recipe
      - POSTGRES_PASSWORD=RecipePassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5444:5432'
volumes:
  postgres: